.releaserc.yml, package.json
This should increase the usability and maintainability in the long run. I thought it was already in the project since I'm using semantic release already. Unfortunately I didn't read the docs, so that's my bad.
I want it, but I don't want to do it.
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
=> fix: add changelog plugin for semantic releases

package.json, src/expo.ts, test/expo.test.ts
Forgot all about that one. Also inspired by the good (and quick) guys from [semantic release themself](https://github.com/semantic-release/npm/pull/71).
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked.
If you're unsure about any of these, don't hesitate to ask. We're here to help!
=> fix: detect indentation and new lines to keep style intact

src/config.ts, src/scripts/verify-conditions.ts, src/types.ts, test/config.test.ts, test/scripts/verify-conditions.test.ts
This decreases configuration overhead and allows the user to define everything once.
=> feature: inherit configuration from prepare when verifying

package.json
The issue causing this is described in [issue #651](https://github.com/kulshekhar/ts-jest/issues/651)
=> refactor: upgrade ts-jest to version 23.1.2

package.json, src/config.ts, src/expo.ts, src/scripts/prepare.ts, src/scripts/verify-conditions.ts, src/types.ts, src/version.ts, test/config.test.ts, test/expo.test.ts, test/factory.ts, test/index.test.ts, test/scripts/prepare.test.ts, test/scripts/verify-conditions.test.ts, test/version-bumpers/index.test.ts, test/version-bumpers/platform-android.test.ts, test/version-bumpers/platform-ios.test.ts, test/version-bumpers/version.test.ts, test/version.test.ts, tslint.json
=> chore: integrate tslint and fix all found issues

package.json
_none, encountered when releasing new version_
=> pipeline: add missing changelog package for releases

package-lock.json, package.json
=> Greenkeeper/@types/node 10.12.22

package-lock.json, package.json
=> Greenkeeper/@commitlint/travis cli 7.5.1

README.md
=> documentation: add missing whitespace

.travis.yml
=> pipeline: audit before downloading dependencies with npm ci

.travis.yml
_none_
This will help to predict the next new version. It helps when creating breaking changes and validating them without actually releasing.
=> pipeline: add dry run of new release on develop

package-lock.json, package.json
=> Greenkeeper/@commitlint/travis cli 7.5.2

package-lock.json, package.json
None, this is a regular maintenance update.
The failed greenkeeper branches should be fixed manually.
=> chore: update all dependencies and manually fix audit warning

package-lock.json, package.json
None, this is a manual greenkeeper fix based on #63
=> Greenkeeper/codecov 3.2.0

package-lock.json, package.json
None, this is a manual greenkeeper fix based on #63
=> Greenkeeper/@types/fs extra 5.0.5

package-lock.json, package.json
None, this is a manual greenkeeper fix based on #63
=> Greenkeeper/@types/node 11.9.5

package-lock.json, package.json
None, this is a manual greenkeeper fix based on #63
=> Greenkeeper/@types/jest 24.0.6

package-lock.json
Fixes security issues related to `js-yaml`.
=> fix: security vulnerability in js-yaml

package-lock.json, package.json
Just an update.
Might look like a breaking change, but it that's not true in our case. See https://github.com/npm/node-semver/blob/master/CHANGELOG.md#60
=> refactor: upgrade semver to version 6.0.0

package-lock.json, package.json
Update branch and see if `ts-jest` issues still persist.
=> refactor: upgrade ts-jest to version 24.0.1

package-lock.json, package.json
Update branch and see if this problem persists.
Fixes #71
=> refactor: upgrade @types/jest to version 24.0.10

package.json
This should make squashing Greenkeeper pull requests way easier.
=> chore: configure pull request titles for greenkeeper

.dependabot/config.yml, package-lock.json, package.json
This is a maintenance release with some security upgrades created by Dependabot.
=> Maintenance release
